version: '3.6'
services:
  kicktipp:
    container_name: kicktipp
    build:
      context: .
    expose:
      - 80
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=kicktipp.eray-ozer.com
      - LETSENCRYPT_HOST=kicktipp.eray-ozer.com
      - LETSENCRYPT_EMAIL=erayozer91@pm.me

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: 'kicktipp_rabbitmq'
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      - nginx-proxy

networks:
  nginx-proxy:
    external: true